#!/bin/bash
# Luuakse muutuja aasta ja väärtus 2016
aasta=2016
# Luuakse muutuja president ja väärtus "Kersti Kaljulaid"
president="Kersti Kaljulaid"
# Luuakse muutuja lause_keskosa ja väärtus ". aastal valiti Eesti presidendiks "
lause_keskosa=". aastal valiti Eesti presidendiks "

# Luuakse muutuja lause
lause="$aasta$lause_keskosa$president"
# Väljastatakse muutuja lause väärtus 
echo "$lause"
