#!/bin/bash
# Skript arvutab, mitu bussi on vaja reisijate vedamiseks, arvestades busside mahutavust.
# Kui reisijad ei mahu täisbussidesse, lisatakse üks buss juurde.

echo -n "Sisesta reisijate arv: "
read reisijad

echo -n "Sisesta kohtade arv bussis: "
read kohad

# Arvutame täisbusside arvu
bussid=$((reisijad / kohad))

# Kui on ülejäävaid reisijaid, lisame ühe bussi juurde
if [ $((reisijad % kohad)) -ne 0 ]; then
    bussid=$((bussid + 1))
fi

echo "Kokku on vaja $bussid bussi"
